name: provider_cli
description: A production-ready Flutter architecture generator CLI with Provider, DI, and modular structure.
version: 0.1.0

homepage: https://github.com/harshitamar/provider_cli
repository: https://github.com/harshitamar/provider_cli
issue_tracker: https://github.com/yourusername/provider_cli/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.5.0
  path: ^1.9.0
dev_dependencies:
  test: ^1.24.0

executables:
  provider_cli:

# include templates (important)
assets:
  - lib/templates/